GET http://localhost:3333/estados

###
PUT http://localhost:3333/estados
Content-Type: application/json

{
    "id": 3,
    "nome": "Acre",
    "sigla": "AC"

}

###

POST http://localhost:3333/cidades
Content-Type: application/json

{
    "nome" : "Itauans",
    "estado_id": 2

}

###
GET http://localhost:3333/cidades

###
GET http://localhost:3333/cidades/1

###
PUT http://localhost:3333/cidades
Content-Type: application/json

{
    "id": 3,
    "nome" : "Itaúna",
    "estado_id": 1

}