GET http://localhost:3333/estados

###
PUT http://localhost:3333/estados
Content-Type: application/json

{
    "id": 3,
    "nome": "Acre",
    "sigla": "AC"

}

###

POST http://localhost:3333/cidades
Content-Type: application/json

{
    "nome" : "Cidade test",
    "estado_id": 2

}

###
GET http://localhost:3333/cidades

###
GET http://localhost:3333/cidades/1

###
PUT http://localhost:3333/cidades
Content-Type: application/json

{
    "id": 4,
    "nome" : "Cidade atualizada",
    "estado_id": 1

}

###
DELETE  http://localhost:3333/cidades
Content-Type: application/json

{
    "id": 4
}

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "nome" : "Fernando B Oliveira",
    "email" : "fboliveira@web.ufop.edu.br",
    "password": "senha"

}

###

POST http://localhost:3333/users/login
Content-Type: application/json

{
    "email" : "fboliveira@web.ufop.edu.br",
    "password": "senha"

}

###

POST http://localhost:3333/users/validate
Content-Type: application/json
Authorization: Bearer App_Doacao eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJmYm9saXZlaXJhQHdlYi51Zm9wLmVkdS5iciIsImxvZ2luRGF0ZSI6IldlZCBNYXIgMjIgMjAyMyAyMToyNTowOCBHTVQtMDMwMCAoQnJhc2lsaWEgU3RhbmRhcmQgVGltZSkiLCJpYXQiOjE2Nzk1MzExMDgsImV4cCI6MTY3OTUzNDcwOH0.S0wcZhMzJHJCEfb8YjCnLnt3TUfGuov4HRiYVMLml7U