@server = http://localhost:5000

###
GET {{server}}

###
GET {{server}}/info

###
GET {{server}}/status

###
GET {{server}}/admin

###
GET {{server}}/api/projects

###
POST {{server}}/api/projects
Content-Type: application/json

{
    "name": "Network"
}

###
PATCH {{server}}/api/projects
Content-Type: application/json

{
    "name": "Network infrastructure",
    "id": 4
}

###
DELETE {{server}}/api/projects
Content-Type: application/json

{
    "id": 4
}

###
GET {{server}}/api/projects/name/b

###
GET {{server}}/api/tasks

###
POST {{server}}/api/tasks
Content-Type: application/json

{
    "description": "Add disks",
    "project_id": 2
}