GET http://localhost:5000/api/projects

###
POST http://localhost:5000/api/projects
Content-Type: application/json

{
    "name": "Backup"
}

###
GET http://localhost:5000/api/projects/end

###
GET http://localhost:5000/api/projects/net/name

###
PATCH  http://localhost:5000/api/projects
Content-Type: application/json

{
    "id": 5,
    "name": "Net"
}

###
DELETE http://localhost:5000/api/projects
Content-Type: application/json

{
    "id": 5
}