GET http://localhost:5000/status

###

GET http://localhost:5000/admin

###
GET http://localhost:5000/api/projects

###
POST http://localhost:5000/api/projects
Content-Type: application/json

{
    "name": "Network"
}

###
GET http://localhost:5000/api/projects/1

###
GET http://localhost:5000/api/projects/name/end

###
PATCH http://localhost:5000/api/projects
Content-Type: application/json

{
    "id": 5,
    "name": "Infra"
}

###
DELETE http://localhost:5000/api/projects
Content-Type: application/json

{
    "id": 5
}

###
GET http://localhost:5000/api/tasks

###
POST http://localhost:5000/api/tasks
Content-Type: application/json

{
    "description": "Teste",
    "project_id": 3
}

###
PATCH  http://localhost:5000/api/tasks
Content-Type: application/json

{
    "id": 6,
    "description": "Testes unitários",
    "project_id": 1
}