# Extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:5550/projects

###
GET http://localhost:5550/projects/1

###
POST http://localhost:5550/projects
Content-Type: application/json

{
    "name": "Teste de rede"
}

###
PATCH http://localhost:5550/projects
Content-Type: application/json

{
    "id": 11,
    "name": "Testes de performance"
}

###
DELETE http://localhost:5550/projects
Content-Type: application/json

{
    "id": 11
}

### 

POST http://localhost:5550/tasks
Content-Type: application/json

{
    "description": "Definição da arquitetura",
    "projectId": 1
}

###
GET http://localhost:5550/tasks

###
GET http://localhost:5550/tasks/2