GET http://localhost:5000

###
GET http://localhost:5000/estados

###
POST http://localhost:5000/estados
Content-Type: application/json

{
    "nome": "São Paulo",
    "sigla": "SP"
}

###
PATCH http://localhost:5000/estados
Content-Type: application/json

{
    "id": 3,
    "nome": "Espírito Santo",
    "sigla": "ES"
}

###
DELETE http://localhost:5000/estados
Content-Type: application/json

{
    "id": 1
}

###

POST http://localhost:5000/cidades
Content-Type: application/json

{
    "nome": "Vitória",
    "estado_id": 3
}

###
PATCH http://localhost:5000/cidades
Content-Type: application/json

{
    "id": 2,
    "nome": "Belo Horizonte",
    "estado_id": 1
}

###
DELETE http://localhost:5000/cidades
Content-Type: application/json

{
    "id": 2
}
